/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parcial2poo;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author lymich
 */
public class FrameInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicio
     */
    public FrameInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        btnPropiedad = new javax.swing.JPanel();
        lblPropiedad = new javax.swing.JLabel();
        btnAgregarProp = new javax.swing.JPanel();
        lblAgregarProp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setUndecorated(true);

        Content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        btnPropiedad.setBackground(new java.awt.Color(204, 204, 255));
        btnPropiedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPropiedadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPropiedadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPropiedadMouseExited(evt);
            }
        });

        lblPropiedad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblPropiedad.setForeground(new java.awt.Color(143, 96, 237));
        lblPropiedad.setText("Propiedades");

        javax.swing.GroupLayout btnPropiedadLayout = new javax.swing.GroupLayout(btnPropiedad);
        btnPropiedad.setLayout(btnPropiedadLayout);
        btnPropiedadLayout.setHorizontalGroup(
            btnPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPropiedadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPropiedad)
                .addGap(49, 49, 49))
        );
        btnPropiedadLayout.setVerticalGroup(
            btnPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPropiedadLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblPropiedad)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnAgregarProp.setBackground(new java.awt.Color(204, 204, 255));
        btnAgregarProp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPropMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarPropMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarPropMouseExited(evt);
            }
        });

        lblAgregarProp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblAgregarProp.setForeground(new java.awt.Color(143, 96, 237));
        lblAgregarProp.setText("Agregar propiedad");

        javax.swing.GroupLayout btnAgregarPropLayout = new javax.swing.GroupLayout(btnAgregarProp);
        btnAgregarProp.setLayout(btnAgregarPropLayout);
        btnAgregarPropLayout.setHorizontalGroup(
            btnAgregarPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarPropLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblAgregarProp)
                .addGap(21, 21, 21))
        );
        btnAgregarPropLayout.setVerticalGroup(
            btnAgregarPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarPropLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblAgregarProp)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btnAgregarProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPropiedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropiedadMouseClicked
        PanelPropiedad p1 = new PanelPropiedad();
        showPanel(p1);
    }//GEN-LAST:event_btnPropiedadMouseClicked

    private void btnPropiedadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropiedadMouseEntered
        btnPropiedad.setBackground(new Color(143,96,237));
        lblPropiedad.setForeground(Color.white);
    }//GEN-LAST:event_btnPropiedadMouseEntered

    private void btnPropiedadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropiedadMouseExited
        btnPropiedad.setBackground(new Color(204,204,255));
        lblPropiedad.setForeground(new Color(143,96,237));
    }//GEN-LAST:event_btnPropiedadMouseExited

    private void btnAgregarPropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPropMouseClicked
        AgregarPropiedad p2 = new AgregarPropiedad();
        showPanel(p2);
    }//GEN-LAST:event_btnAgregarPropMouseClicked

    private void btnAgregarPropMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPropMouseEntered
        btnAgregarProp.setBackground(new Color(143,96,237));
        lblAgregarProp.setForeground(Color.white);
    }//GEN-LAST:event_btnAgregarPropMouseEntered

    private void btnAgregarPropMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPropMouseExited
        btnAgregarProp.setBackground(new Color(204,204,255));
        lblAgregarProp.setForeground(new Color(143,96,237));
    }//GEN-LAST:event_btnAgregarPropMouseExited

    private void showPanel(JPanel p) {
        p.setSize(765, 591);
        p.setLocation(0, 0);
        Content.removeAll();
        Content.add(p, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel btnAgregarProp;
    private javax.swing.JPanel btnPropiedad;
    private javax.swing.JLabel lblAgregarProp;
    private javax.swing.JLabel lblPropiedad;
    // End of variables declaration//GEN-END:variables
}
